//--------------------------------------------------------------------------------
// Transaction Class (mem_seq_item):
//
// Represents a single memory transaction used for communication between
// verification components. It contains all the information required to
// perform read and write operations on the memory DUT.
//
// Randomized Variables:
// - wr_rd : Defines the transaction type (1: Write, 0: Read).
// - addr  : Random address generated for memory access (`ADDR_WIDTH-1:0).
// - wdata : Random write data used during write operations (`WIDTH-1:0).
// - valid : Controls the validity of the transaction request (rand for protocol variation).
//
// Non-Random / Response Variables:
// - rdata : Stores the data received from the DUT during read operations.
// - ready : Captures the DUT's handshake response indicating operation completion.
//
// Purpose:
// Acts as a data packet generated by the sequence/generator, driven by the driver,
// monitored by the monitor, and verified by the scoreboard against a reference model.
//--------------------------------------------------------------------------------
class mem_tx;
	// random veriable
	rand  bit wr_rd;
	randc bit [`ADDR_WIDTH-1:0]addr;
	rand  bit [`WIDTH-1:0]     wdata;
	      bit [`WIDTH-1:0]     rdata;
	rand  bit                  valid;
	      bit                  ready;


//	function void print(input string str="mem_tx");
// 		$display("----------------------%0s-----------------------",str);
//		$display("wr_rd=%0d",wr_rd);
//		$display("addr =%0d",addr);
//		$display("wdata=%0d",wdata);
//		$display("rdata=%0d",rdata);
//		$display("valid=%0d",valid);
//		$display("ready=%0d",ready);
//	endfunction
endclass
